### ISSUE TITLE
Tests failing with Invalid JSON RPC response

### ISSUE THREAD

**Issue by maurelian** [SetProtocol/set-protocol-contracts#231]
To Repro:

1. Run `yarn run chain`
2. In another terminal `yarn run test`

I'm on master at commit ffc256e. I realize that's a bit behind this repo, but am unable to re-run the test 

```
.....
  269 passing (8m)
  8 failing

  1) Contract: RebalancingSetTokenFactory
       "before each" hook:
     Uncaught Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2/lib/xhr2.js:544:12)
      at ClientRequest.<anonymous> (node_modules/xhr2/lib/xhr2.js:414:24)
      at TLSSocket.socketErrorListener (_http_client.js:395:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  2) Contract: RebalancingSetToken
       "before each" hook:
     Uncaught Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2/lib/xhr2.js:544:12)
      at ClientRequest.<anonymous> (node_modules/xhr2/lib/xhr2.js:414:24)
      at TLSSocket.socketErrorListener (_http_client.js:395:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  3) Contract: RebalancingSetToken
       "after each" hook:
     Uncaught Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2/lib/xhr2.js:544:12)
      at ClientRequest.<anonymous> (node_modules/xhr2/lib/xhr2.js:414:24)
      at TLSSocket.socketErrorListener (_http_client.js:395:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  4) Contract: Core
       "before all" hook: prepare suite:
     Uncaught Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2/lib/xhr2.js:544:12)
      at ClientRequest.<anonymous> (node_modules/xhr2/lib/xhr2.js:414:24)
      at TLSSocket.socketErrorListener (_http_client.js:395:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  5) Contract: Authorizable
       "before all" hook: prepare suite:
     Uncaught Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2/lib/xhr2.js:544:12)
      at ClientRequest.<anonymous> (node_modules/xhr2/lib/xhr2.js:414:24)
      at TLSSocket.socketErrorListener (_http_client.js:395:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  6) Contract: ERC20WrapperMock
       "before all" hook: prepare suite:
     Uncaught Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2/lib/xhr2.js:544:12)
      at ClientRequest.<anonymous> (node_modules/xhr2/lib/xhr2.js:414:24)
      at TLSSocket.socketErrorListener (_http_client.js:395:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  7) Contract: Bytes32Mock
       "before all" hook: prepare suite:
     Uncaught Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2/lib/xhr2.js:544:12)
      at ClientRequest.<anonymous> (node_modules/xhr2/lib/xhr2.js:414:24)
      at TLSSocket.socketErrorListener (_http_client.js:395:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  8) Contract: CommonMathMock
       "before all" hook: prepare suite:
     Uncaught Error: Invalid JSON RPC response: ""
      at Object.InvalidResponse (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:115:32)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpRequestError (node_modules/xhr2/lib/xhr2.js:544:12)
      at ClientRequest.<anonymous> (node_modules/xhr2/lib/xhr2.js:414:24)
      at TLSSocket.socketErrorListener (_http_client.js:395:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by maurelian** [comment]
Actually, upon pulling again I'm now getting error on the `tsc` step:

```$ tsc
test/core/exchange-wrappers/kyberNetworkWrapper.spec.ts:6:26 - error TS2305: Module '"/home/primary/Projects/Scoping/set-protocol-contracts/node_modules/set-protocol-utils/dist/types/index"' has no exported member 'KyberTrade'.

6 import { Address, Bytes, KyberTrade } from 'set-protocol-utils';
                           ~~~~~~~~~~


test/core/exchange-wrappers/kyberNetworkWrapper.spec.ts:52:20 - error TS2339: Property 'KYBER_NETWORK_PROXY_ADDRESS' does not exist on type 'typeof SetProtocolTestUtils'.

52       SetTestUtils.KYBER_NETWORK_PROXY_ADDRESS,
   
...                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by felix2feng** [comment]
@maurelian Perhaps you need to `yarn install` again?

**Comment by maurelian** [comment]
Yep, that was it!
